defaults:
- quantizer: lattice
- dataset: ffhq1024
- _self_

general:
  entity: entity
  project: ll-vq-vae
  seed: 392
  device: 0

optimizer:
  learning_rate: 1e-3
  scheduler_gamma: 0.0
  weight_decay: 0.0
